Переполнение и пиксель перфект
htmlacademy-htmlcss/1838315-sedona-32 pull request #16
Opened 2021-11-12 21:28 UTC by Solarevtk

2021-11-12 21:29 UTC, Solarevtk commented
проверьте пожалуйста код-ревью

2021-11-14 12:56 UTC, blckwltz requested changes
@Solarevtk комментарии по критериям:
- TEST-01 ➕ 
- TEST-02 ➕ 
- TEST-03 ➕ 
- TEST-04 https://tppr.me/p61Qg https://tppr.me/oIvob https://tppr.me/6QJq0 https://tppr.me/hz57J https://tppr.me/g0WZe
- TEST-05 ➕ 
- TEST-06 https://tppr.me/gPO24 https://tppr.me/RoJUQ https://tppr.me/yOsu2 https://tppr.me/EDLK7
- TEST-07 нужно еще раз проверить все состояния интерактивных элементов по стайлгайду, сейчас есть несоответствия
- TEST-08 https://tppr.me/jBwdM высота поля увеличивается при фокусе
- PROJ-01 ➕ 
- PROJ-02 ➕ 
- PROJ-03 ➕ 
- PROJ-04 ➕ 
- HTML-01-06 ➕ 
- HTML-07 ➖  проверить можно здесь
- HTML-08 ➖ 
- CSS, IMG, CONT, ALLY ➕

2021-11-15 08:28 UTC, blckwltz commented
@Solarevtk не исправлено:
- TEST-04 https://tppr.me/65Syw
- TEST-06 (расположение модальных окон https://tppr.me/4OV7W)
- TEST-08
- HTML-07

2021-11-17 21:25 UTC, blckwltz reviewed
@Solarevtk нужно поправить адреса всех ссылок, должно быть так:

На главной:

- Главная - без адреса
- О Седоне - любой адрес
- Гостиницы - catalog.html
- Логотип - без адреса

На странице гостиниц:
- Главная - index.html
- О Седоне - любой адрес
- Гостиницы - без адреса
- Логотип - index.html

По возможности хорошо бы везде избавиться от позиционирования элементов с помощью position: relative, это скорее всего не пройдет на защите.
Лучше не позиционировать элементы таким образом, это будет вызывать проблемы при изменении количества контента и добавлении или удалении других элементов.
Элементы в потоке должны позиционироваться только с помощью margin/padding.
position: relative нужно использовать в тех случаях, когда относительно этого элемента нужно позиционировать другой с position: absolute

2021-11-17 21:25 UTC, blckwltz commented on styles/style.css
> +.navigation-link[href="about-sedona.html"]{
@Solarevtk такие селекторы лучше не использовать, адреса могут поменяться и придется их переписывать

2021-11-17 21:25 UTC, blckwltz commented on styles/style.css
> +    position: absolute;
@Solarevtk здесь аналогично предыдущему комментарию

2021-11-17 21:25 UTC, merged